import test from 'node:test';
import assert from 'node:assert/strict';
import { evaluate, Game, RESIDUALS, CUES } from './engine.mjs';

// Independent transcription of the 24-row Rin v0.3 oracle. These are EXPECTED values,
// not generated by the evaluate() function being tested.
const ORACLE = [
  ['MCB','H',[0,1,2],[1],['H','R1','R2']],
  ['MCK','R1',[0,1],[1],['R1']],
  ['MBC','R2',[1,2],[1],['R2']],
  ['MBK','R3',[1,2],[2],['R3']],
  ['MKC','R0',[],[],[]],
  ['MKB','R3',[1,2],[1],['R3']],
  ['CMB','R1',[0,1],[0],['R1']],
  ['CMK','R1',[0,1],[0],['R1']],
  ['CBM','R2',[0,1],[1],['R2']],
  ['CBK','R2',[0,1],[1],['R2','R3']],
  ['CKM','R0',[],[],[]],
  ['CKB','R3',[1,2],[1],['R3']],
  ['BMC','R1',[1,2],[2],['R1']],
  ['BMK','R0',[],[],[]],
  ['BCM','H',[0,1,2],[1],['H','R1','R2']],
  ['BCK','R2',[0,1],[0],['R2']],
  ['BKM','R3',[0,1],[1],['R3']],
  ['BKC','R3',[0,1],[1],['R3']],
  ['KMC','R1',[1,2],[2],['R1']],
  ['KMB','R0',[],[],[]],
  ['KCM','R1',[1,2],[1],['R1']],
  ['KCB','R2',[1,2],[2],['R2']],
  ['KBM','R3',[0,1],[0],['R3']],
  ['KBC','R2',[1,2],[1],['R2','R3']],
];
const fill = (game, code) => { [...code].forEach((item, i) => assert.equal(game.place(item, i), true)); };

// F01 + F07: complete permutation oracle, priority, causes, visible information, repeatability.
test('F01/F07 — all 24 arrangements match Rin v0.3 across five repeats', () => {
  const seen = new Set();
  const distribution = { H:0, R1:0, R2:0, R3:0, R0:0 };
  for (const [code, reactionId, causeSlots, visibleClueSlots, matchedRuleIds] of ORACLE) {
    assert.equal(seen.has(code), false, `duplicate oracle row ${code}`); seen.add(code);
    distribution[reactionId]++;
    for (let repeat = 0; repeat < 5; repeat++) {
      const source = [...code], before = [...source];
      const r = evaluate(source);
      assert.deepEqual(source, before, `evaluate modified input ${code}`);
      assert.equal(r.reactionId, reactionId, `${code} reaction`);
      assert.deepEqual(r.causeSlots, causeSlots, `${code} internal cause`);
      assert.deepEqual(r.visibleClueSlots, visibleClueSlots, `${code} public clue`);
      assert.deepEqual(r.matchedRuleIds, matchedRuleIds, `${code} matched rules`);
      assert.equal(r.residualChange, RESIDUALS[reactionId], `${code} residual`);
      assert.equal(r.evidenceCueId, CUES[reactionId], `${code} presentation cue`);
      assert.ok(r.visibleClueSlots.length <= 1);
      for (const n of [...r.causeSlots, ...r.visibleClueSlots]) assert.ok(n >= 0 && n <= 2);
    }
  }
  assert.equal(seen.size, 24);
  assert.deepEqual(distribution, { H:2, R1:6, R2:6, R3:6, R0:4 });
});

test('F02 — hidden and base collisions select only the first priority', () => {
  for (const code of ['MCB','BCM']) assert.equal(evaluate([...code]).reactionId, 'H');
  for (const code of ['CBK','KBC']) {
    assert.deepEqual(evaluate([...code]).matchedRuleIds, ['R2','R3']);
    assert.equal(evaluate([...code]).reactionId, 'R2');
  }
});

test('F03 — incomplete/duplicate/invalid, nonreaction and tray -1 guard', () => {
  for (const slots of [[null,null,null],['M','C',null],['M','M','C'],['M','C','X'],['M','C']]) {
    assert.throws(() => evaluate(slots), TypeError);
  }
  assert.equal(evaluate(['M','B','K']).reactionId, 'R3'); // C in tray must NOT act adjacent to M
  assert.equal(evaluate(['B','M','K']).reactionId, 'R0');
  assert.equal(evaluate(['M','K','C']).reactionId, 'R0');
  const g = new Game();
  assert.equal(g.open(), false); fill(g, 'MCK'); assert.equal(g.open(), true);
  assert.equal(g.state.phase, 'REACT'); g.skip(); assert.equal(g.state.phase, 'RESULT');
  assert.equal(g.rearrange(), true); assert.equal(g.state.phase, 'READY');
  assert.deepEqual(g.state.slots, ['M','C','K']);
});

test('F03/F08 — tap selected and drag route are identical; replace/swap/move never duplicate', () => {
  const tap = new Game(), drag = new Game();
  for (const [item, index] of [['M',0],['C',1],['K',2]]) {
    tap.select(item); assert.equal(tap.placeSelected(index), true);
    assert.equal(drag.place(item, index, 'drag'), true);
  }
  assert.deepEqual(tap.state.slots, drag.state.slots);
  assert.deepEqual(evaluate(tap.state.slots), evaluate(drag.state.slots));
  assert.equal(tap.place('M',1), true); // swap M and C
  assert.deepEqual(tap.state.slots, ['C','M','K']);
  assert.equal(tap.place('B',1), true); // tray B replaces M, M returns to tray
  assert.deepEqual(tap.state.slots, ['C','B','K']);
  assert.equal(tap.place('C',2), true); // swap C and K
  assert.deepEqual(tap.state.slots, ['K','B','C']);
  assert.equal(new Set(tap.state.slots).size, 3);
  const partial = new Game(); partial.place('K',0); partial.place('K',2); // move to empty
  assert.deepEqual(partial.state.slots, [null,null,'K']); assert.equal(partial.open(), false);
});

test('F04/F09 — REACT input guard, snapshot, skipped exactly once, late callback no-op', () => {
  const g = new Game(); fill(g, 'MCB'); assert.equal(g.open(), true);
  const {runId, slotSnapshot, result} = g.state;
  assert.equal(g.open(), false); assert.equal(g.place('K',2), false); assert.equal(g.select('K'), false);
  assert.deepEqual(g.state.slotSnapshot, slotSnapshot); assert.equal(g.state.phase, 'REACT');
  assert.equal(g.skip(), true); assert.equal(g.skip(), false); assert.equal(g.advance(runId), false);
  assert.equal(g.state.phase, 'RESULT'); assert.equal(g.state.result.reactionId, result.reactionId);
  assert.equal(g.state.result.residualChange, result.residualChange);
  assert.equal(g.state.history.length, 1);
  assert.equal(g.rearrange(), true); assert.equal(g.state.history.length, 1);
  assert.equal(g.open(), true); assert.equal(g.advance(runId), false);
  assert.equal(g.state.animationStep, 'CUE');
  assert.equal(g.state.history.length, 1);
});

test('F04/F09 — full progression and reset invalidate earlier run IDs', () => {
  const g = new Game(); fill(g, 'MCK'); g.open(); const previousId = g.state.runId;
  for (const beat of ['GAZE','ACTION','RESIDUE']) { assert.equal(g.advance(previousId), true); assert.equal(g.state.animationStep, beat); }
  assert.equal(g.advance(previousId), true); assert.equal(g.state.phase, 'RESULT');
  assert.equal(g.state.history.length, 1);
  g.rearrange(); g.open(); const old = g.state.runId;
  g.reset(); assert.equal(g.state.phase, 'PLACE'); assert.deepEqual(g.state.slots, [null,null,null]);
  assert.equal(g.state.result, null); assert.equal(g.state.history.length, 0);
  fill(g, 'BCM'); g.open(); assert.equal(g.advance(old), false);
  assert.equal(g.state.result.reactionId, 'H'); assert.equal(g.state.animationStep, 'CUE');
});

test('F05 — background completes once without re-evaluating or releasing edit lock early', () => {
  const g = new Game(); fill(g, 'MKC'); g.open(); const runId = g.state.runId;
  assert.equal(g.resumeAfterBackground(), true);
  assert.equal(g.state.phase, 'RESULT'); assert.equal(g.state.result.reactionId, 'R0');
  assert.equal(g.resumeAfterBackground(), false); assert.equal(g.advance(runId), false);
  assert.equal(g.state.history.length, 1); assert.equal(g.place('B',0), false);
  g.rearrange(); assert.deepEqual(g.state.slots, ['M','K','C']);
});

test('snapshot/result/debug returned to UI are copies, not mutable engine state', () => {
  const g = new Game(); fill(g, 'MCK'); g.open();
  const ui = g.state; ui.slots[0] = 'B'; ui.slotSnapshot[0] = 'B';
  ui.result.causeSlots.push(9); ui.result.visibleClueSlots.push(9); ui.history.push({});
  const current = g.state;
  assert.deepEqual(current.slots, ['M','C','K']); assert.deepEqual(current.slotSnapshot, ['M','C','K']);
  assert.deepEqual(current.result.causeSlots, [0,1]); assert.deepEqual(current.result.visibleClueSlots, [1]);
  assert.equal(current.history.length, 0);
});
